apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: testgo0122aa 
  janus-idp.io/tekton: testgo0122aa
  backstage.io/kubernetes-id: testgo0122aa
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: testgo0122aa
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  