apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: testgo0122aa-gitops
  description: This is GitOps manifest for testgo0122aa   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: testgo0122aa
    backstage.io/kubernetes-id: testgo0122aa 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: xjiangorg/testgo0122aa-gitops   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:testgo0122aa
